# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerberus < Formula
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"
  version "1.12.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.1/cerberus_1.12.1_darwin_amd64.tar.gz"
      sha256 "91b0ed1dc5c8037c6e7eb44f3f2c56645ceca7a30628cc67a3c240e31f63c723"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.1/cerberus_1.12.1_darwin_arm64.tar.gz"
      sha256 "2bb0a635333f760890164e2a26010f1170ae5755ff54960245db11321ecaba93"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.1/cerberus_1.12.1_linux_amd64.tar.gz"
      sha256 "1d51b2ecf42318d881ba623061d1c3cc5117d1bb563a42a87e88aa550c143853"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.1/cerberus_1.12.1_linux_arm64.tar.gz"
      sha256 "86200bbd40045b8eea7045aac0bc46b9a14dcfdd7e39b8f132b22fc7b1cbc283"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  test do
    system "#{bin}/cerberus", "--version"
  end
end
