# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerberus < Formula
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"
  version "1.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.0/cerberus_1.12.0_darwin_amd64.tar.gz"
      sha256 "aa786a99654ae236d911aabaaeae3909fc23fb8fa039ea5464d208668fdc65aa"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.0/cerberus_1.12.0_darwin_arm64.tar.gz"
      sha256 "ad1682a13d6afe72ff40be68791d7b445f54130010a9f23c8936ae2d6787bbfb"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.0/cerberus_1.12.0_linux_amd64.tar.gz"
      sha256 "8fcfe55ff30806d916640eea6b8c73eb492eea06f515fe626275f949046fc2f0"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.12.0/cerberus_1.12.0_linux_arm64.tar.gz"
      sha256 "b1de6250187181212fd7e4f4a94accf0ac58c9f8e8624f6e6d3c42e6f2342199"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  test do
    system "#{bin}/cerberus", "--version"
  end
end
