# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerberus" do
  version "1.15.0"

  on_macos do
    on_intel do
      sha256 "cb133582a0056316c2d1b55caf3a8f0d0743c9ea7abe855d63b1b4267da804e5"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5299823b9d70696a469e0af92be471d6ffcfe9b21b00619cabf5f874361d670"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "016724716bc69b455f82b0fb1ecfa82aa71e57c89ab09d9b273791c38790ba15"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aecc9cf118a74ab3d4333440b03ee8c18c3de3013fb7822f04cdff6d1a3d1613"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cerberus"
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerberus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerberus"]
    end
  end

  # No zap stanza required

end
