# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerberus" do
  version "1.15.4"

  on_macos do
    on_intel do
      sha256 "a9d330703026cfabe96e3dd4c60ccf050fb16219c409a443928536c3fbba4c7d"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be6f9ffd838fd7b7108c644460b571f8b48ba74ae9c1f661a696f515dccbd080"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f2cb2a19532bf39a440b0603b1424afc75c62cbbd8e025c79593fbac8047ab9"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b19787a0afff46f95a910cc0a369ac8e0ad7b39490db593363c9a3e3dfa45744"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cerberus"
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerberus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerberus"]
    end
  end

  # No zap stanza required

end
