# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerberus" do
  version "1.13.3"

  on_macos do
    on_intel do
      sha256 "8243f0fcb50c8fed36eeb0b26408e1a3126fc604c6d8df31d997d7887e8b95fd"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e20e51205ea9efd4da44ca095c6adae11064e427d3125f7be00b0cbe2af35b6e"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2c828837ea0beb05a6aa6c24ea327018c2ebc903683666d74b088f05efaa652"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8fabee5f01feeab8f52ac313f12206262e2cc42b82afd07e642c5ea4bf6345c"
      url "https://github.com/tsouza/cerberus/releases/download/v#{version}/cerberus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cerberus"
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerberus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerberus"]
    end
  end

  # No zap stanza required

end
