# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerberus < Formula
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"
  version "1.13.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.1/cerberus_1.13.1_darwin_amd64.tar.gz"
      sha256 "75d9bcb1ac86a2ce7a6cfb374799dbe64f5e90ec06ffa1936132c1af532ba2be"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.1/cerberus_1.13.1_darwin_arm64.tar.gz"
      sha256 "5f821f2023e0b02e0a29c059cbbbaf0b34b5e79f31bb604ad09ffe8cca07f42b"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.1/cerberus_1.13.1_linux_amd64.tar.gz"
      sha256 "92d34e285c1f33fd18576f10ddf6a3d2646cac81ce6ea60f414187cc92277030"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.1/cerberus_1.13.1_linux_arm64.tar.gz"
      sha256 "c5e9b590cdf72d6d7ca2e3376782865bb97f073f472ec9c9f3667730b88ce644"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  test do
    system "#{bin}/cerberus", "--version"
  end
end
