# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerberus < Formula
  desc "Drop-in Prometheus / Loki / Tempo HTTP gateway for ClickHouse"
  homepage "https://github.com/tsouza/cerberus"
  version "1.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.0/cerberus_1.13.0_darwin_amd64.tar.gz"
      sha256 "ef4eca38c9fabb07ada78626baf7b6241d228a710983ab3956208ba6ce2a5785"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.0/cerberus_1.13.0_darwin_arm64.tar.gz"
      sha256 "83b67d5c10f83df23160414ab42bd455966c975fb7e59cfa2078e3d28477da7b"

      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.0/cerberus_1.13.0_linux_amd64.tar.gz"
      sha256 "af3cd458ac0feb9508ae3ea65b54dd313cdfbdcd78e4802f9720b513a738e609"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsouza/cerberus/releases/download/v1.13.0/cerberus_1.13.0_linux_arm64.tar.gz"
      sha256 "61b3612fb721816d4faaeb6ddc9f31fecbf57eb5a53c29f085c30f7b13401228"
      define_method(:install) do
        bin.install "cerberus"
      end
    end
  end

  test do
    system "#{bin}/cerberus", "--version"
  end
end
